name: pixabay
description: "A new Flutter project."
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.6
  dio: ^5.0.9
  retrofit: ^4.4.1
  json_annotation: ^4.8.1
  flutter_bloc: ^8.1.6
  equatable: ^2.0.3
  json_serializable: ^6.8.0
  http: ^1.2.2
  rxdart: ^0.28.0

dev_dependencies:
  flutter_lints: ^4.0.0
  build_runner: ^2.4.12
  retrofit_generator: ^9.1.2

  flutter_test:
    sdk: flutter



flutter:

  uses-material-design: true
